# Generated by Django 3.2.7 on 2021-09-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Middle_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=7)),
                ('Address', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.CharField(max_length=10)),
                ('Alternate_Email', models.EmailField(max_length=254)),
                ('Alternate_Mobile', models.CharField(max_length=10)),
                ('Father_Name', models.CharField(max_length=50)),
                ('Mother_Name', models.CharField(max_length=50)),
                ('Institute_Name', models.CharField(max_length=50)),
                ('Branch_Name', models.CharField(max_length=50)),
            ],
        ),
    ]
